import type { Metadata } from "next";

import { Inter } from "next/font/google";
import Header from "./components/Header";
import HeroSec from "./components/HeroSec";
import Footer from "./components/Footer";
import JobBoard from "./components/JobBoard";
import Form from "./components/Form";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Board",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <header>
//           <Header />
//         </header>
//         <div>
//           <HeroSec></HeroSec>
//         </div>
//         <div>
//           <JobBoard></JobBoard>
//         </div>
//         {/* <div>
//           <Form />
//   </div> */}
//         <footer>
//           <Footer />
//         </footer>
//         <main> { children }</main>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <Header />

          <main> { children }</main>
          <Footer />

        
      </body>
    </html>
  );
}
